services:
  - type: web
    name: dogtalkpro-relaxboy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        fromDatabase:
          name: dogtalkpro
          property: port
